"""Core-owned model metadata store from free public sources (BOD-108).

OmniRoute is never the metadata source of truth. Callers later (BOD-100) should
use :func:`lookup_omniroute_id` and :meth:`MetadataLookup.provenance_for_receipt`.
"""

from verdict.metadata.mapping import IdentityMap, default_mapping_path, load_identity_map
from verdict.metadata.records import (
    CAP_FIELDS,
    DROP_MAP_TARGET_MISSING,
    DROP_REQUIRED_UNKNOWN,
    DROP_STALE,
    DROP_UNMAPPED,
    METADATA_SCHEMA_VERSION,
    SCORE_FIELDS,
    SOURCE_ARENA_ELO,
    SOURCE_ARTIFICIAL_ANALYSIS,
    SOURCE_BFCL,
    SOURCE_LITELLM,
    SOURCE_MODELS_DEV,
    SOURCE_MODELS_DEV_MODELS,
    SOURCE_OPEN_LLM,
    CapabilityCaps,
    FieldProvenance,
    MetadataDrop,
    MetadataLookup,
    ModelMetadataError,
    ModelMetadataRecord,
    ProvenancedField,
    SoftScores,
    SourceStatus,
    resolve_required_name,
)
from verdict.metadata.sources import (
    LITELLM_URL,
    MODELS_DEV_API_URL,
    MODELS_DEV_MODELS_URL,
    P1_SKIP_REASONS,
    FixtureTransport,
    HttpxJsonTransport,
)
from verdict.metadata.store import (
    MetadataSnapshot,
    default_store_path,
    file_transport,
    load_store,
    lookup_omniroute_id,
    refresh_metadata,
    save_store,
)

__all__ = [
    "CAP_FIELDS",
    "DROP_MAP_TARGET_MISSING",
    "DROP_REQUIRED_UNKNOWN",
    "DROP_STALE",
    "DROP_UNMAPPED",
    "LITELLM_URL",
    "METADATA_SCHEMA_VERSION",
    "MODELS_DEV_API_URL",
    "MODELS_DEV_MODELS_URL",
    "P1_SKIP_REASONS",
    "SCORE_FIELDS",
    "SOURCE_ARENA_ELO",
    "SOURCE_ARTIFICIAL_ANALYSIS",
    "SOURCE_BFCL",
    "SOURCE_LITELLM",
    "SOURCE_MODELS_DEV",
    "SOURCE_MODELS_DEV_MODELS",
    "SOURCE_OPEN_LLM",
    "CapabilityCaps",
    "FieldProvenance",
    "FixtureTransport",
    "HttpxJsonTransport",
    "IdentityMap",
    "MetadataDrop",
    "MetadataLookup",
    "MetadataSnapshot",
    "ModelMetadataError",
    "ModelMetadataRecord",
    "ProvenancedField",
    "SoftScores",
    "SourceStatus",
    "default_mapping_path",
    "default_store_path",
    "file_transport",
    "load_identity_map",
    "load_store",
    "lookup_omniroute_id",
    "refresh_metadata",
    "resolve_required_name",
    "save_store",
]
