"""Public verdict contracts, routing, planning, and availability interfaces."""

from __future__ import annotations

import importlib
from typing import Any

__version__ = "0.5.0"

# BOD-321: lazy public re-exports via PEP 562 module __getattr__.
# Importing `verdict` must not eagerly import heavy submodules (httpx, benchmarking,
# comparison, gate, intelligence, admit_prove_confirm, free_tier_admit, ...).
# Each name below resolves on first attribute access and is cached on the module,
# so repeated access after the first is a plain attribute lookup (no re-import cost).
# `verdict.__all__` and every `from verdict import X` for X below keep working unchanged.
_LAZY_ATTRS: dict[str, str] = {
    "AvailabilityCandidate": "verdict.availability",
    "AvailabilityReport": "verdict.availability",
    "AvailabilityState": "verdict.availability",
    "CallableOmniRouteTransport": "verdict.availability",
    "CandidateRequirements": "verdict.availability",
    "MappingOmniRouteTransport": "verdict.availability",
    "OmniRouteAvailabilityAdapter": "verdict.availability",
    "OmniRouteTransport": "verdict.availability",
    "OmniRouteTransportError": "verdict.availability",
    "OmniRouteTransportMalformed": "verdict.availability",
    "OmniRouteTransportTimeout": "verdict.availability",
    "OmniRouteTransportUnauthorized": "verdict.availability",
    "OmniRouteTransportUnsupported": "verdict.availability",
    "RuntimeObservation": "verdict.availability",
    "StaticOmniRouteTransport": "verdict.availability",
    "discover_transport_capabilities": "verdict.availability",
    "AvailabilityCache": "verdict.availability_cache",
    "CacheKey": "verdict.availability_cache",
    "build_cache_report": "verdict.availability_cache",
    "explain_freshness": "verdict.availability_cache",
    "DEFAULT_FIXTURE_PATH": "verdict.benchmarking",
    "format_benchmark_report": "verdict.benchmarking",
    "load_benchmark_fixture": "verdict.benchmarking",
    "run_reproducible_benchmarks": "verdict.benchmarking",
    "CAPABILITY_PASSPORT_SCHEMA_VERSION": "verdict.capability_passports",
    "EVIDENCE_AUTHORITY_SCHEMA_VERSION": "verdict.capability_passports",
    "CapabilityDecision": "verdict.capability_passports",
    "CapabilityEvidence": "verdict.capability_passports",
    "CapabilityPassport": "verdict.capability_passports",
    "CapabilityPassportError": "verdict.capability_passports",
    "CapabilityStatus": "verdict.capability_passports",
    "EvidenceAuthority": "verdict.capability_passports",
    "RouteIdentity": "verdict.capability_passports",
    "CLAIMS_LEDGER_SCHEMA_VERSION": "verdict.claims_ledger",
    "Claim": "verdict.claims_ledger",
    "ClaimHydrationOmission": "verdict.claims_ledger",
    "ClaimHydrationResult": "verdict.claims_ledger",
    "ClaimsLedger": "verdict.claims_ledger",
    "ClaimsLedgerError": "verdict.claims_ledger",
    "ClaimStatus": "verdict.claims_ledger",
    "ClaimTransition": "verdict.claims_ledger",
    "ClaimTransitionError": "verdict.claims_ledger",
    "FreshnessPolicy": "verdict.claims_ledger",
    "FreshnessResult": "verdict.claims_ledger",
    "FreshnessStatus": "verdict.claims_ledger",
    "evaluate_claim_freshness": "verdict.claims_ledger",
    "hydrate_claims": "verdict.claims_ledger",
    "CONTEXT_SCHEMA_VERSION": "verdict.context_pack",
    "ContextContractError": "verdict.context_pack",
    "ContextDecision": "verdict.context_pack",
    "ContextPack": "verdict.context_pack",
    "ContextPackCompiler": "verdict.context_pack",
    "ContextPackSlot": "verdict.context_pack",
    "ContextPlan": "verdict.context_pack",
    "ContextReceipt": "verdict.context_pack",
    "ContextUnit": "verdict.context_pack",
    "AvailabilitySnapshot": "verdict.contracts",
    "CapabilityRequirement": "verdict.contracts",
    "ContractValidationError": "verdict.contracts",
    "ExecutionEnvelope": "verdict.contracts",
    "FallbackAttempt": "verdict.contracts",
    "LearningEvent": "verdict.contracts",
    "OutcomeEpisode": "verdict.contracts",
    "OutcomeEvent": "verdict.contracts",
    "RoutingDecisionContract": "verdict.contracts",
    "RuntimeCandidate": "verdict.contracts",
    "TaskEpisode": "verdict.contracts",
    "TaskSpec": "verdict.contracts",
    "TaskWorkflowOutcomeEpisode": "verdict.contracts",
    "VerificationPlan": "verdict.contracts",
    "WorkflowEpisode": "verdict.contracts",
    "WorkflowPlan": "verdict.contracts",
    "AssignmentExplanation": "verdict.dispatcher",
    "Dispatcher": "verdict.dispatcher",
    "DispatchPolicy": "verdict.dispatcher",
    "DispatchResult": "verdict.dispatcher",
    "SwarmDispatcher": "verdict.dispatcher",
    "EVALUATION_SCHEMA_VERSION": "verdict.evaluation",
    "CounterfactualResult": "verdict.evaluation",
    "EvaluationCase": "verdict.evaluation",
    "EvaluationController": "verdict.evaluation",
    "EvaluationError": "verdict.evaluation",
    "EvaluationFailureClass": "verdict.evaluation",
    "EvaluationObservation": "verdict.evaluation",
    "EvaluationReport": "verdict.evaluation",
    "EvaluationStatus": "verdict.evaluation",
    "EvaluationSuite": "verdict.evaluation",
    "EvaluationVariant": "verdict.evaluation",
    "PromotionDecision": "verdict.evaluation",
    "PromotionPolicy": "verdict.evaluation",
    "PromotionState": "verdict.evaluation",
    "VariantSummary": "verdict.evaluation",
    "VerificationStatus": "verdict.evaluation",
    "build_evaluation_report": "verdict.evaluation",
    "counterfactual_from_receipt": "verdict.evaluation",
    "normalize_failure_class": "verdict.evaluation",
    "AmbiguousEvidenceSelectorError": "verdict.evidence",
    "EvidenceStore": "verdict.evidence",
    "ExplainEvidence": "verdict.evidence",
    "build_outcome_event": "verdict.evidence",
    "build_routing_decision_contract": "verdict.evidence",
    "request_features": "verdict.evidence",
    "EvidenceItem": "verdict.evidence_receipts",
    "EvidenceReceipt": "verdict.evidence_receipts",
    "ReceiptKind": "verdict.evidence_receipts",
    "Gate": "verdict.gate",
    "TELEMETRY_FIELDS": "verdict.gateway_adapter_runtime",
    "AdapterFailureSignal": "verdict.gateway_adapter_runtime",
    "AdapterResponseMetadata": "verdict.gateway_adapter_runtime",
    "GatewayAdapter": "verdict.gateway_adapter_runtime",
    "NormalizedFailure": "verdict.gateway_adapter_runtime",
    "RouteIdentityAttestation": "verdict.gateway_adapter_runtime",
    "TelemetryValue": "verdict.gateway_adapter_runtime",
    "validate_telemetry": "verdict.gateway_adapter_runtime",
    "GATEWAY_ADAPTER_CONTRACT_VERSION": "verdict.gateway_adapters",
    "AdapterCapability": "verdict.gateway_adapters",
    "AdapterDiscoveryMetadata": "verdict.gateway_adapters",
    "AdapterManifest": "verdict.gateway_adapters",
    "AdapterRequest": "verdict.gateway_adapters",
    "AdapterRouteIdentity": "verdict.gateway_adapters",
    "CapabilityNegotiation": "verdict.gateway_adapters",
    "CapabilitySupport": "verdict.gateway_adapters",
    "GatewayAdapterError": "verdict.gateway_adapters",
    "NormalizedFailureClass": "verdict.gateway_adapters",
    "TranslatedRequest": "verdict.gateway_adapters",
    "ConformanceCheck": "verdict.gateway_conformance",
    "ConformanceReport": "verdict.gateway_conformance",
    "run_conformance": "verdict.gateway_conformance",
    "run_gateway_adapter_conformance": "verdict.gateway_conformance",
    "GuidanceConfig": "verdict.guidance",
    "GuidanceConfigurationError": "verdict.guidance",
    "GuidanceControlPlane": "verdict.guidance",
    "GuidanceRule": "verdict.guidance",
    "GuidanceStatus": "verdict.guidance",
    "GuidanceUnavailableError": "verdict.guidance",
    "IntelligenceService": "verdict.intelligence",
    "ReadinessReport": "verdict.intelligence",
    "ADAPTER_PROTOCOL_VERSION": "verdict.memory_adapters",
    "MANIFEST_VERSION": "verdict.memory_adapters",
    "AdapterDescriptor": "verdict.memory_adapters",
    "AdapterIngestionReport": "verdict.memory_adapters",
    "AdapterIngestionSummary": "verdict.memory_adapters",
    "AdapterRegistry": "verdict.memory_adapters",
    "AdapterResolution": "verdict.memory_adapters",
    "AdapterStatus": "verdict.memory_adapters",
    "AdapterUnavailableError": "verdict.memory_adapters",
    "DocumentMemoryAdapter": "verdict.memory_adapters",
    "ImportPolicy": "verdict.memory_adapters",
    "ManifestError": "verdict.memory_adapters",
    "ManifestRecordsAdapter": "verdict.memory_adapters",
    "ManifestReport": "verdict.memory_adapters",
    "build_default_adapter_registry": "verdict.memory_adapters",
    "content_hash": "verdict.memory_adapters",
    "export_manifest": "verdict.memory_adapters",
    "import_manifest": "verdict.memory_adapters",
    "DEFAULT_CHUNK_SIZE": "verdict.memory_document_adapter",
    "DOCUMENT_ADAPTER_VERSION": "verdict.memory_document_adapter",
    "DocumentIngestionPolicy": "verdict.memory_document_adapter",
    "DocumentIngestionReport": "verdict.memory_document_adapter",
    "DocumentIngestionResult": "verdict.memory_document_adapter",
    "DocumentIngestor": "verdict.memory_document_adapter",
    "DocumentIssue": "verdict.memory_document_adapter",
    "GATE_VERSION": "verdict.memory_gate",
    "AuthorityLevel": "verdict.memory_gate",
    "MemoryGate": "verdict.memory_gate",
    "MemoryGateEvent": "verdict.memory_gate",
    "MemoryGovernor": "verdict.memory_gate",
    "MemoryNamespace": "verdict.memory_gate",
    "MemoryPolicy": "verdict.memory_gate",
    "MemoryWriteRequest": "verdict.memory_gate",
    "MemoryWriteResult": "verdict.memory_gate",
    "MemoryPlane": "verdict.memory_plane",
    "MemoryRecord": "verdict.memory_plane",
    "MemorySearchResult": "verdict.memory_plane",
    "SessionAdapter": "verdict.memory_session_adapter",
    "SessionFormatDescriptor": "verdict.memory_session_adapter",
    "SessionImportPolicy": "verdict.memory_session_adapter",
    "SessionImportReport": "verdict.memory_session_adapter",
    "SessionImportResult": "verdict.memory_session_adapter",
    "import_session": "verdict.memory_session_adapter",
    "normalize_session_record": "verdict.memory_session_adapter",
    "session_record_to_memory_record": "verdict.memory_session_adapter",
    "verify_session_manifest": "verdict.memory_session_adapter",
    "ModelInfo": "verdict.models",
    "ProviderConfig": "verdict.models",
    "RoutingDecision": "verdict.models",
    "OmniRouteHTTPTransport": "verdict.omniroute",
    "CATALOG_QUALIFICATION_VERSION": "verdict.omniroute_catalog",
    "CatalogProjectionReconciliation": "verdict.omniroute_catalog",
    "CatalogQualificationError": "verdict.omniroute_catalog",
    "CatalogQualificationReport": "verdict.omniroute_catalog",
    "CatalogSnapshot": "verdict.omniroute_catalog",
    "ProbeQualification": "verdict.omniroute_catalog",
    "probe_catalog": "verdict.omniroute_catalog",
    "qualify_catalog": "verdict.omniroute_catalog",
    "reconcile_catalog_projections": "verdict.omniroute_catalog",
    "select_probe_models": "verdict.omniroute_catalog",
    "store_qualification": "verdict.omniroute_catalog",
    "summarize_probes": "verdict.omniroute_catalog",
    "FailureClass": "verdict.planner",
    "IntakePlanner": "verdict.planner",
    "PlannerPolicy": "verdict.planner",
    "PlanningResult": "verdict.planner",
    "PlanningUnavailable": "verdict.planner",
    "PlanRejected": "verdict.planner",
    "PlanResult": "verdict.planner",
    "StructuredPlanner": "verdict.planner",
    "WorkflowKind": "verdict.planner",
    "WorkflowSelector": "verdict.planner",
    "POLICY_SCHEMA_VERSION": "verdict.policy",
    "POLICY_VERSION": "verdict.policy",
    "DecisionState": "verdict.policy",
    "EligibilityCompilation": "verdict.policy",
    "Policy": "verdict.policy",
    "PolicyCandidate": "verdict.policy",
    "PolicyDecision": "verdict.policy",
    "PolicyValidationError": "verdict.policy",
    "compile_policy": "verdict.policy",
    "explain_policy": "verdict.policy",
    "migrate_task_policy": "verdict.policy",
    "ARTIFACT_SCHEMA_VERSION": "verdict.policy_artifacts",
    "SignedPolicyDecisionArtifact": "verdict.policy_artifacts",
    "PROBE_DIAGNOSTICS_VERSION": "verdict.probes",
    "PROBE_PROMPT": "verdict.probes",
    "ProbeBudget": "verdict.probes",
    "ProbeConsentRequiredError": "verdict.probes",
    "ProbeObservation": "verdict.probes",
    "ProbePolicy": "verdict.probes",
    "ProbeRegistry": "verdict.probes",
    "ProbeResponseTooLargeError": "verdict.probes",
    "ProbeRun": "verdict.probes",
    "ProbeRunDiagnostics": "verdict.probes",
    "ProbeRunner": "verdict.probes",
    "openai_probe_transport": "verdict.probes",
    "ClaimRecord": "verdict.proof_receipts",
    "DropReason": "verdict.proof_receipts",
    "EvidenceReference": "verdict.proof_receipts",
    "ProofReceipt": "verdict.proof_receipts",
    "ProofReceiptError": "verdict.proof_receipts",
    "SourceReference": "verdict.proof_receipts",
    "build_proof_receipt": "verdict.proof_receipts",
    "build_receipt_manifest": "verdict.proof_receipts",
    "claim_hash": "verdict.proof_receipts",
    "CHAT_NON_STREAM_CASE": "verdict.protocol_probes",
    "CHAT_STREAM_CASE": "verdict.protocol_probes",
    "PROTOCOL_PROBE_CASES": "verdict.protocol_probes",
    "PROTOCOL_PROBE_PROMPT": "verdict.protocol_probes",
    "PROTOCOL_PROBE_VERSION": "verdict.protocol_probes",
    "RESPONSES_NON_STREAM_CASE": "verdict.protocol_probes",
    "RESPONSES_STREAM_CASE": "verdict.protocol_probes",
    "ProtocolProbeCase": "verdict.protocol_probes",
    "ProtocolProbeConsentRequiredError": "verdict.protocol_probes",
    "ProtocolProbeObservation": "verdict.protocol_probes",
    "ProtocolProbePolicy": "verdict.protocol_probes",
    "ProtocolProbeRunner": "verdict.protocol_probes",
    "ProtocolProbeTransport": "verdict.protocol_probes",
    "ProtocolSurface": "verdict.protocol_probes",
    "PROVIDER_RECEIPT_SCHEMA_VERSION": "verdict.provider_receipts",
    "ProviderReceipt": "verdict.provider_receipts",
    "build_provider_receipt": "verdict.provider_receipts",
    "canonical_hash": "verdict.provider_receipts",
    "IndependentReceiptVerifier": "verdict.receipt_verifier",
    "ReceiptVerifier": "verdict.receipt_verifier",
    "VerificationResult": "verdict.receipt_verifier",
    "verify_manifest": "verdict.receipt_verifier",
    "verify_receipt": "verdict.receipt_verifier",
    "verify_serialized_manifest": "verdict.receipt_verifier",
    "verify_serialized_receipt": "verdict.receipt_verifier",
    "NVIDIA_RESPONSES_COMPATIBILITY_RULE": "verdict.responses_compatibility",
    "RESPONSES_COMPATIBILITY_RULE_VERSION": "verdict.responses_compatibility",
    "RESPONSES_COMPATIBILITY_RULES": "verdict.responses_compatibility",
    "ResponsesCompatibilityError": "verdict.responses_compatibility",
    "ResponsesCompatibilityRule": "verdict.responses_compatibility",
    "adapt_responses_payload": "verdict.responses_compatibility",
    "RUNTIME_COMPATIBILITY_SCHEMA_VERSION": "verdict.runtime_compatibility",
    "RuntimeCapabilityAssessment": "verdict.runtime_compatibility",
    "RuntimeCompatibilityEntry": "verdict.runtime_compatibility",
    "RuntimeCompatibilityReport": "verdict.runtime_compatibility",
    "RuntimeCompatibilityStatus": "verdict.runtime_compatibility",
    "build_runtime_compatibility_report": "verdict.runtime_compatibility",
    "DEFAULT_RUNTIME_STATE_DIR": "verdict.runtime_contract",
    "RUNTIME_CONTRACT_VERSION": "verdict.runtime_contract",
    "OwnershipRecord": "verdict.runtime_contract",
    "ProcessInspector": "verdict.runtime_contract",
    "ProcessSnapshot": "verdict.runtime_contract",
    "RuntimeManagerError": "verdict.runtime_contract",
    "RuntimePlan": "verdict.runtime_contract",
    "RuntimeProcess": "verdict.runtime_contract",
    "RuntimeServiceSpec": "verdict.runtime_contract",
    "default_service_specs": "verdict.runtime_contract",
    "ProcfsInspector": "verdict.runtime_daemons",
    "RuntimeManager": "verdict.runtime_daemons",
    "RUNTIME_HEALTH_SCHEMA_VERSION": "verdict.runtime_health",
    "RuntimeHealthError": "verdict.runtime_health",
    "RuntimeHealthObservation": "verdict.runtime_health",
    "RuntimeHealthReport": "verdict.runtime_health",
    "RuntimeHealthStatus": "verdict.runtime_health",
    "build_runtime_health_report": "verdict.runtime_health",
    "RUNTIME_PASSPORT_SCHEMA_VERSION": "verdict.runtime_passports",
    "RuntimeCapabilityDecision": "verdict.runtime_passports",
    "RuntimeCapabilityPassport": "verdict.runtime_passports",
    "RuntimePassportError": "verdict.runtime_passports",
    "RuntimeSubjectIdentity": "verdict.runtime_passports",
    "RuntimeSubjectKind": "verdict.runtime_passports",
    "STRENGTH_PROFILE_SCHEMA_VERSION": "verdict.strength_profiles",
    "StrengthAggregate": "verdict.strength_profiles",
    "StrengthFailureClass": "verdict.strength_profiles",
    "StrengthObservation": "verdict.strength_profiles",
    "StrengthProfileError": "verdict.strength_profiles",
    "aggregate_strength": "verdict.strength_profiles",
    "CHAT_STRICT_OUTPUT_CASE": "verdict.structured_qualification",
    "RESPONSES_STRICT_OUTPUT_CASE": "verdict.structured_qualification",
    "STRICT_RESULT_SCHEMA": "verdict.structured_qualification",
    "STRUCTURED_OUTPUT_CASES": "verdict.structured_qualification",
    "STRUCTURED_QUALIFICATION_VERSION": "verdict.structured_qualification",
    "StrictSchemaError": "verdict.structured_qualification",
    "StructuredOutputCase": "verdict.structured_qualification",
    "StructuredOutputObservation": "verdict.structured_qualification",
    "StructuredOutputRunner": "verdict.structured_qualification",
    "StructuredQualificationConsentRequiredError": "verdict.structured_qualification",
    "StructuredQualificationTransport": "verdict.structured_qualification",
    "validate_json_instance": "verdict.structured_qualification",
    "validate_strict_schema": "verdict.structured_qualification",
    "SUBAGENT_ROLE_REQUIREMENTS": "verdict.subagent_models",
    "SubagentModelSelector": "verdict.subagent_models",
    "get_subagent_selector": "verdict.subagent_models",
    "select_model_for_role": "verdict.subagent_models",
    "select_models_for_parallel_roles": "verdict.subagent_models",
    "resolve_subagent_model": "verdict.subagent_resolver",
    "TOOL_ERROR_RECOVERY_CASE": "verdict.tool_qualification",
    "TOOL_INJECTION_RESISTANCE_CASE": "verdict.tool_qualification",
    "TOOL_LIFECYCLE_CASES": "verdict.tool_qualification",
    "TOOL_MAX_OUTPUT_TOKENS": "verdict.tool_qualification",
    "TOOL_PARALLEL_CALLS_CASE": "verdict.tool_qualification",
    "TOOL_QUALIFICATION_VERSION": "verdict.tool_qualification",
    "TOOL_RESPONSES_ERROR_RECOVERY_CASE": "verdict.tool_qualification",
    "TOOL_RESPONSES_INJECTION_RESISTANCE_CASE": "verdict.tool_qualification",
    "TOOL_RESPONSES_PARALLEL_CALLS_CASE": "verdict.tool_qualification",
    "TOOL_RESPONSES_RESULT_CONSUMPTION_CASE": "verdict.tool_qualification",
    "TOOL_RESPONSES_TERMINATION_CASE": "verdict.tool_qualification",
    "TOOL_RESPONSES_UNAVAILABLE_CASE": "verdict.tool_qualification",
    "TOOL_RESPONSES_VALID_ARGUMENTS_CASE": "verdict.tool_qualification",
    "TOOL_RESULT_CONSUMPTION_CASE": "verdict.tool_qualification",
    "TOOL_TERMINATION_CASE": "verdict.tool_qualification",
    "TOOL_UNAVAILABLE_CASE": "verdict.tool_qualification",
    "TOOL_VALID_ARGUMENTS_CASE": "verdict.tool_qualification",
    "ToolDefinition": "verdict.tool_qualification",
    "ToolHandler": "verdict.tool_qualification",
    "ToolLifecycleCase": "verdict.tool_qualification",
    "ToolLifecycleObservation": "verdict.tool_qualification",
    "ToolLifecycleRunner": "verdict.tool_qualification",
    "ToolQualificationConsentRequiredError": "verdict.tool_qualification",
    "ByteState": "verdict.transitions",
    "ExecutionContext": "verdict.transitions",
    "RetrySafety": "verdict.transitions",
    "TransitionCompiler": "verdict.transitions",
    "TransitionEdge": "verdict.transitions",
    "TransitionGraph": "verdict.transitions",
    "TransitionKind": "verdict.transitions",
    "TransitionValidationError": "verdict.transitions",
    "OmniRouteWorkerClient": "verdict.workers",
    "WorkerError": "verdict.workers",
    "WorkerModel": "verdict.workers",
    "WorkerPool": "verdict.workers",
    "WorkerRequest": "verdict.workers",
    "WorkerResult": "verdict.workers",
    "WorkerUnavailable": "verdict.workers",
}


def __getattr__(name: str) -> Any:
    """Resolve public re-exports lazily (PEP 562) to keep `import verdict` cheap."""
    module_name = _LAZY_ATTRS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = importlib.import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Keep dir(verdict) and introspection showing the full public surface."""
    return sorted(set(globals()) | set(_LAZY_ATTRS))


__all__ = [
    "ADAPTER_PROTOCOL_VERSION",
    "ARTIFACT_SCHEMA_VERSION",
    "CAPABILITY_PASSPORT_SCHEMA_VERSION",
    "CATALOG_QUALIFICATION_VERSION",
    "CHAT_NON_STREAM_CASE",
    "CHAT_STREAM_CASE",
    "CHAT_STRICT_OUTPUT_CASE",
    "CLAIMS_LEDGER_SCHEMA_VERSION",
    "CONTEXT_SCHEMA_VERSION",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_FIXTURE_PATH",
    "DEFAULT_RUNTIME_STATE_DIR",
    "DOCUMENT_ADAPTER_VERSION",
    "EVALUATION_SCHEMA_VERSION",
    "EVIDENCE_AUTHORITY_SCHEMA_VERSION",
    "GATEWAY_ADAPTER_CONTRACT_VERSION",
    "GATE_VERSION",
    "MANIFEST_VERSION",
    "NVIDIA_RESPONSES_COMPATIBILITY_RULE",
    "POLICY_SCHEMA_VERSION",
    "POLICY_VERSION",
    "PROBE_DIAGNOSTICS_VERSION",
    "PROBE_PROMPT",
    "PROTOCOL_PROBE_CASES",
    "PROTOCOL_PROBE_PROMPT",
    "PROTOCOL_PROBE_VERSION",
    "PROVIDER_RECEIPT_SCHEMA_VERSION",
    "RESPONSES_COMPATIBILITY_RULES",
    "RESPONSES_COMPATIBILITY_RULE_VERSION",
    "RESPONSES_NON_STREAM_CASE",
    "RESPONSES_STREAM_CASE",
    "RESPONSES_STRICT_OUTPUT_CASE",
    "RUNTIME_COMPATIBILITY_SCHEMA_VERSION",
    "RUNTIME_CONTRACT_VERSION",
    "RUNTIME_HEALTH_SCHEMA_VERSION",
    "RUNTIME_PASSPORT_SCHEMA_VERSION",
    "STRENGTH_PROFILE_SCHEMA_VERSION",
    "STRICT_RESULT_SCHEMA",
    "STRUCTURED_OUTPUT_CASES",
    "STRUCTURED_QUALIFICATION_VERSION",
    "SUBAGENT_ROLE_REQUIREMENTS",
    "TELEMETRY_FIELDS",
    "TOOL_ERROR_RECOVERY_CASE",
    "TOOL_INJECTION_RESISTANCE_CASE",
    "TOOL_LIFECYCLE_CASES",
    "TOOL_MAX_OUTPUT_TOKENS",
    "TOOL_PARALLEL_CALLS_CASE",
    "TOOL_QUALIFICATION_VERSION",
    "TOOL_RESPONSES_ERROR_RECOVERY_CASE",
    "TOOL_RESPONSES_INJECTION_RESISTANCE_CASE",
    "TOOL_RESPONSES_PARALLEL_CALLS_CASE",
    "TOOL_RESPONSES_RESULT_CONSUMPTION_CASE",
    "TOOL_RESPONSES_TERMINATION_CASE",
    "TOOL_RESPONSES_UNAVAILABLE_CASE",
    "TOOL_RESPONSES_VALID_ARGUMENTS_CASE",
    "TOOL_RESULT_CONSUMPTION_CASE",
    "TOOL_TERMINATION_CASE",
    "TOOL_UNAVAILABLE_CASE",
    "TOOL_VALID_ARGUMENTS_CASE",
    "AdapterCapability",
    "AdapterDescriptor",
    "AdapterDiscoveryMetadata",
    "AdapterFailureSignal",
    "AdapterIngestionReport",
    "AdapterIngestionSummary",
    "AdapterManifest",
    "AdapterRegistry",
    "AdapterRequest",
    "AdapterResolution",
    "AdapterResponseMetadata",
    "AdapterRouteIdentity",
    "AdapterStatus",
    "AdapterUnavailableError",
    "AmbiguousEvidenceSelectorError",
    "AssignmentExplanation",
    "AuthorityLevel",
    "AvailabilityCache",
    "AvailabilityCandidate",
    "AvailabilityReport",
    "AvailabilitySnapshot",
    "AvailabilityState",
    "ByteState",
    "CacheKey",
    "CallableOmniRouteTransport",
    "CandidateRequirements",
    "CapabilityDecision",
    "CapabilityEvidence",
    "CapabilityNegotiation",
    "CapabilityPassport",
    "CapabilityPassportError",
    "CapabilityRequirement",
    "CapabilityStatus",
    "CapabilitySupport",
    "CatalogProjectionReconciliation",
    "CatalogQualificationError",
    "CatalogQualificationReport",
    "CatalogSnapshot",
    "Claim",
    "ClaimHydrationOmission",
    "ClaimHydrationResult",
    "ClaimRecord",
    "ClaimStatus",
    "ClaimTransition",
    "ClaimTransitionError",
    "ClaimsLedger",
    "ClaimsLedgerError",
    "ConformanceCheck",
    "ConformanceReport",
    "ContextContractError",
    "ContextDecision",
    "ContextPack",
    "ContextPackCompiler",
    "ContextPackSlot",
    "ContextPlan",
    "ContextReceipt",
    "ContextUnit",
    "ContractValidationError",
    "CounterfactualResult",
    "DecisionState",
    "DispatchPolicy",
    "DispatchResult",
    "Dispatcher",
    "DocumentIngestionPolicy",
    "DocumentIngestionReport",
    "DocumentIngestionResult",
    "DocumentIngestor",
    "DocumentIssue",
    "DocumentMemoryAdapter",
    "DropReason",
    "EligibilityCompilation",
    "EvaluationCase",
    "EvaluationController",
    "EvaluationError",
    "EvaluationFailureClass",
    "EvaluationObservation",
    "EvaluationReport",
    "EvaluationStatus",
    "EvaluationSuite",
    "EvaluationVariant",
    "EvidenceAuthority",
    "EvidenceItem",
    "EvidenceReceipt",
    "EvidenceReference",
    "EvidenceStore",
    "ExecutionContext",
    "ExecutionEnvelope",
    "ExplainEvidence",
    "FailureClass",
    "FallbackAttempt",
    "FreshnessPolicy",
    "FreshnessResult",
    "FreshnessStatus",
    "Gate",
    "GatewayAdapter",
    "GatewayAdapterError",
    "GuidanceConfig",
    "GuidanceConfigurationError",
    "GuidanceControlPlane",
    "GuidanceRule",
    "GuidanceStatus",
    "GuidanceUnavailableError",
    "ImportPolicy",
    "IndependentReceiptVerifier",
    "IntakePlanner",
    "IntelligenceService",
    "LearningEvent",
    "ManifestError",
    "ManifestRecordsAdapter",
    "ManifestReport",
    "MappingOmniRouteTransport",
    "MemoryGate",
    "MemoryGateEvent",
    "MemoryGovernor",
    "MemoryNamespace",
    "MemoryPlane",
    "MemoryPolicy",
    "MemoryRecord",
    "MemorySearchResult",
    "MemoryWriteRequest",
    "MemoryWriteResult",
    "ModelInfo",
    "NormalizedFailure",
    "NormalizedFailureClass",
    "OmniRouteAvailabilityAdapter",
    "OmniRouteHTTPTransport",
    "OmniRouteTransport",
    "OmniRouteTransportError",
    "OmniRouteTransportMalformed",
    "OmniRouteTransportTimeout",
    "OmniRouteTransportUnauthorized",
    "OmniRouteTransportUnsupported",
    "OmniRouteWorkerClient",
    "OutcomeEpisode",
    "OutcomeEvent",
    "OwnershipRecord",
    "PlanRejected",
    "PlanResult",
    "PlannerPolicy",
    "PlanningResult",
    "PlanningUnavailable",
    "Policy",
    "PolicyCandidate",
    "PolicyDecision",
    "PolicyValidationError",
    "ProbeBudget",
    "ProbeConsentRequiredError",
    "ProbeObservation",
    "ProbePolicy",
    "ProbeQualification",
    "ProbeRegistry",
    "ProbeResponseTooLargeError",
    "ProbeRun",
    "ProbeRunDiagnostics",
    "ProbeRunner",
    "ProcessInspector",
    "ProcessSnapshot",
    "ProcfsInspector",
    "PromotionDecision",
    "PromotionPolicy",
    "PromotionState",
    "ProofReceipt",
    "ProofReceiptError",
    "ProtocolProbeCase",
    "ProtocolProbeConsentRequiredError",
    "ProtocolProbeObservation",
    "ProtocolProbePolicy",
    "ProtocolProbeRunner",
    "ProtocolProbeTransport",
    "ProtocolSurface",
    "ProviderConfig",
    "ProviderReceipt",
    "ReadinessReport",
    "ReceiptKind",
    "ReceiptVerifier",
    "ResponsesCompatibilityError",
    "ResponsesCompatibilityRule",
    "RetrySafety",
    "RouteIdentity",
    "RouteIdentityAttestation",
    "RoutingDecision",
    "RoutingDecisionContract",
    "RuntimeCandidate",
    "RuntimeCapabilityAssessment",
    "RuntimeCapabilityDecision",
    "RuntimeCapabilityPassport",
    "RuntimeCompatibilityEntry",
    "RuntimeCompatibilityReport",
    "RuntimeCompatibilityStatus",
    "RuntimeHealthError",
    "RuntimeHealthObservation",
    "RuntimeHealthReport",
    "RuntimeHealthStatus",
    "RuntimeManager",
    "RuntimeManagerError",
    "RuntimeObservation",
    "RuntimePassportError",
    "RuntimePlan",
    "RuntimeProcess",
    "RuntimeServiceSpec",
    "RuntimeSubjectIdentity",
    "RuntimeSubjectKind",
    "SessionAdapter",
    "SessionFormatDescriptor",
    "SessionImportPolicy",
    "SessionImportReport",
    "SessionImportResult",
    "SignedPolicyDecisionArtifact",
    "SourceReference",
    "StaticOmniRouteTransport",
    "StrengthAggregate",
    "StrengthFailureClass",
    "StrengthObservation",
    "StrengthProfileError",
    "StrictSchemaError",
    "StructuredOutputCase",
    "StructuredOutputObservation",
    "StructuredOutputRunner",
    "StructuredPlanner",
    "StructuredQualificationConsentRequiredError",
    "StructuredQualificationTransport",
    "SubagentModelSelector",
    "SwarmDispatcher",
    "TaskEpisode",
    "TaskSpec",
    "TaskWorkflowOutcomeEpisode",
    "TelemetryValue",
    "ToolDefinition",
    "ToolHandler",
    "ToolLifecycleCase",
    "ToolLifecycleObservation",
    "ToolLifecycleRunner",
    "ToolQualificationConsentRequiredError",
    "TransitionCompiler",
    "TransitionEdge",
    "TransitionGraph",
    "TransitionKind",
    "TransitionValidationError",
    "TranslatedRequest",
    "VariantSummary",
    "VerificationPlan",
    "VerificationResult",
    "VerificationStatus",
    "WorkerError",
    "WorkerModel",
    "WorkerPool",
    "WorkerRequest",
    "WorkerResult",
    "WorkerUnavailable",
    "WorkflowEpisode",
    "WorkflowKind",
    "WorkflowPlan",
    "WorkflowSelector",
    "adapt_responses_payload",
    "aggregate_strength",
    "build_cache_report",
    "build_default_adapter_registry",
    "build_evaluation_report",
    "build_outcome_event",
    "build_proof_receipt",
    "build_provider_receipt",
    "build_receipt_manifest",
    "build_routing_decision_contract",
    "build_runtime_compatibility_report",
    "build_runtime_health_report",
    "canonical_hash",
    "claim_hash",
    "compile_policy",
    "content_hash",
    "counterfactual_from_receipt",
    "default_service_specs",
    "discover_transport_capabilities",
    "evaluate_claim_freshness",
    "explain_freshness",
    "explain_policy",
    "export_manifest",
    "format_benchmark_report",
    "get_subagent_selector",
    "hydrate_claims",
    "import_manifest",
    "import_session",
    "load_benchmark_fixture",
    "migrate_task_policy",
    "normalize_failure_class",
    "normalize_session_record",
    "openai_probe_transport",
    "probe_catalog",
    "qualify_catalog",
    "reconcile_catalog_projections",
    "request_features",
    "resolve_subagent_model",
    "run_conformance",
    "run_gateway_adapter_conformance",
    "run_reproducible_benchmarks",
    "select_model_for_role",
    "select_models_for_parallel_roles",
    "select_probe_models",
    "session_record_to_memory_record",
    "store_qualification",
    "summarize_probes",
    "validate_json_instance",
    "validate_strict_schema",
    "validate_telemetry",
    "verify_manifest",
    "verify_receipt",
    "verify_serialized_manifest",
    "verify_serialized_receipt",
    "verify_session_manifest",
]
