"""Public llm-gate contracts, routing, planning, and availability interfaces."""

from llm_gate.availability import (
    AvailabilityCandidate,
    AvailabilityReport,
    AvailabilityState,
    CandidateRequirements,
    OmniRouteAvailabilityAdapter,
    OmniRouteTransport,
    RuntimeObservation,
    StaticOmniRouteTransport,
)
from llm_gate.benchmarking import (
    DEFAULT_FIXTURE_PATH,
    format_benchmark_report,
    load_benchmark_fixture,
    run_reproducible_benchmarks,
)
from llm_gate.contracts import (
    AvailabilitySnapshot,
    CapabilityRequirement,
    ContractValidationError,
    FallbackAttempt,
    LearningEvent,
    OutcomeEpisode,
    OutcomeEvent,
    RoutingDecisionContract,
    RuntimeCandidate,
    TaskEpisode,
    TaskSpec,
    TaskWorkflowOutcomeEpisode,
    VerificationPlan,
    WorkflowEpisode,
    WorkflowPlan,
)
from llm_gate.dispatcher import (
    AssignmentExplanation,
    Dispatcher,
    DispatchPolicy,
    DispatchResult,
    SwarmDispatcher,
)
from llm_gate.gate import Gate
from llm_gate.intelligence import IntelligenceService, ReadinessReport
from llm_gate.models import ModelInfo, ProviderConfig, RoutingDecision
from llm_gate.planner import (
    FailureClass,
    IntakePlanner,
    PlannerPolicy,
    PlanningResult,
    PlanningUnavailable,
    PlanRejected,
    PlanResult,
    StructuredPlanner,
    WorkflowKind,
    WorkflowSelector,
)

__all__ = [
    "AssignmentExplanation",
    "AvailabilityCandidate",
    "AvailabilityReport",
    "AvailabilitySnapshot",
    "AvailabilityState",
    "DEFAULT_FIXTURE_PATH",
    "CandidateRequirements",
    "CapabilityRequirement",
    "ContractValidationError",
    "DispatchPolicy",
    "DispatchResult",
    "Dispatcher",
    "FailureClass",
    "FallbackAttempt",
    "format_benchmark_report",
    "Gate",
    "IntakePlanner",
    "IntelligenceService",
    "LearningEvent",
    "load_benchmark_fixture",
    "ModelInfo",
    "OmniRouteAvailabilityAdapter",
    "OmniRouteTransport",
    "OutcomeEpisode",
    "OutcomeEvent",
    "PlanRejected",
    "PlanResult",
    "PlannerPolicy",
    "PlanningResult",
    "PlanningUnavailable",
    "ProviderConfig",
    "ReadinessReport",
    "RoutingDecisionContract",
    "RoutingDecision",
    "RuntimeCandidate",
    "RuntimeObservation",
    "run_reproducible_benchmarks",
    "StaticOmniRouteTransport",
    "StructuredPlanner",
    "StructuredPlanner",
    "TaskEpisode",
    "TaskSpec",
    "TaskWorkflowOutcomeEpisode",
    "VerificationPlan",
    "WorkflowEpisode",
    "WorkflowKind",
    "WorkflowPlan",
    "WorkflowSelector",
]

__version__ = "0.1.0"
