"""Public llm-gate contracts, routing, planning, and availability interfaces."""

from llm_gate.availability import (
    AvailabilityCandidate,
    AvailabilityReport,
    AvailabilityState,
    CallableOmniRouteTransport,
    CandidateRequirements,
    MappingOmniRouteTransport,
    OmniRouteAvailabilityAdapter,
    OmniRouteTransport,
    OmniRouteTransportError,
    OmniRouteTransportMalformed,
    OmniRouteTransportTimeout,
    OmniRouteTransportUnauthorized,
    OmniRouteTransportUnsupported,
    RuntimeObservation,
    StaticOmniRouteTransport,
    discover_transport_capabilities,
)
from llm_gate.availability_cache import (
    AvailabilityCache,
    CacheKey,
    build_cache_report,
    explain_freshness,
)
from llm_gate.benchmarking import (
    DEFAULT_FIXTURE_PATH,
    format_benchmark_report,
    load_benchmark_fixture,
    run_reproducible_benchmarks,
)
from llm_gate.contracts import (
    AvailabilitySnapshot,
    CapabilityRequirement,
    ContractValidationError,
    FallbackAttempt,
    LearningEvent,
    OutcomeEpisode,
    OutcomeEvent,
    RoutingDecisionContract,
    RuntimeCandidate,
    TaskEpisode,
    TaskSpec,
    TaskWorkflowOutcomeEpisode,
    VerificationPlan,
    WorkflowEpisode,
    WorkflowPlan,
)
from llm_gate.dispatcher import (
    AssignmentExplanation,
    Dispatcher,
    DispatchPolicy,
    DispatchResult,
    SwarmDispatcher,
)
from llm_gate.gate import Gate
from llm_gate.intelligence import IntelligenceService, ReadinessReport
from llm_gate.models import ModelInfo, ProviderConfig, RoutingDecision
from llm_gate.omniroute import OmniRouteHTTPTransport
from llm_gate.planner import (
    FailureClass,
    IntakePlanner,
    PlannerPolicy,
    PlanningResult,
    PlanningUnavailable,
    PlanRejected,
    PlanResult,
    StructuredPlanner,
    WorkflowKind,
    WorkflowSelector,
)
from llm_gate.probes import (
    PROBE_PROMPT,
    ProbeObservation,
    ProbePolicy,
    ProbeRegistry,
    ProbeRunner,
    openai_probe_transport,
)

__all__ = [
    "DEFAULT_FIXTURE_PATH",
    "PROBE_PROMPT",
    "AssignmentExplanation",
    "AvailabilityCache",
    "AvailabilityCandidate",
    "AvailabilityReport",
    "AvailabilitySnapshot",
    "AvailabilityState",
    "CacheKey",
    "CallableOmniRouteTransport",
    "CandidateRequirements",
    "CapabilityRequirement",
    "ContractValidationError",
    "DispatchPolicy",
    "DispatchResult",
    "Dispatcher",
    "FailureClass",
    "FallbackAttempt",
    "Gate",
    "IntakePlanner",
    "IntelligenceService",
    "LearningEvent",
    "MappingOmniRouteTransport",
    "ModelInfo",
    "OmniRouteAvailabilityAdapter",
    "OmniRouteHTTPTransport",
    "OmniRouteTransport",
    "OmniRouteTransportError",
    "OmniRouteTransportMalformed",
    "OmniRouteTransportTimeout",
    "OmniRouteTransportUnauthorized",
    "OmniRouteTransportUnsupported",
    "OutcomeEpisode",
    "OutcomeEvent",
    "PlanRejected",
    "PlanResult",
    "PlannerPolicy",
    "PlanningResult",
    "PlanningUnavailable",
    "ProbeObservation",
    "ProbePolicy",
    "ProbeRegistry",
    "ProbeRunner",
    "ProviderConfig",
    "ReadinessReport",
    "RoutingDecision",
    "RoutingDecisionContract",
    "RuntimeCandidate",
    "RuntimeObservation",
    "StaticOmniRouteTransport",
    "StructuredPlanner",
    "SwarmDispatcher",
    "TaskEpisode",
    "TaskSpec",
    "TaskWorkflowOutcomeEpisode",
    "VerificationPlan",
    "WorkflowEpisode",
    "WorkflowKind",
    "WorkflowPlan",
    "WorkflowSelector",
    "build_cache_report",
    "discover_transport_capabilities",
    "explain_freshness",
    "format_benchmark_report",
    "load_benchmark_fixture",
    "openai_probe_transport",
    "run_reproducible_benchmarks",
]

__version__ = "0.1.0"
