#!/usr/bin/env python3
"""Generate docs/cli/PARITY_MATRIX.md from the action registry + CLI parsers.

Run: python scripts/gen_parity_matrix.py
"""

from __future__ import annotations

import argparse
from pathlib import Path


def _walk_parsers() -> list[str]:
    """Walk the real argparse tree and return every registered top-level command.

    Replicates the parser construction from ``verdict.cli.main()`` exactly,
    then adds orchestration subcommands and any dispatch-only commands that
    don't have their own parsers_* registrar.
    """
    from verdict.commands import (
        parsers_autodev,
        parsers_credentials,
        parsers_harness,
        parsers_models,
        parsers_openspec,
        parsers_routing,
        parsers_runtime,
        parsers_setup,
    )

    parser = argparse.ArgumentParser()
    subs = parser.add_subparsers(dest="command")

    for registrar in (
        parsers_setup,
        parsers_credentials,
        parsers_routing,
        parsers_autodev,
        parsers_harness,
        parsers_runtime,
        parsers_models,
        parsers_openspec,
    ):
        registrar.register(subs)

    registered: set[str] = set()
    for action in parser._subparsers._group_actions:
        if isinstance(action, argparse._SubParsersAction):
            registered.update(action.choices.keys())

    dispatch_only = [
        "compare",
        "suggest",
        "doctor",
        "receipt",
        "replay",
        "simulate",
        "memory",
        "mcp",
        "hook",
        "uninstall",
        "check",
        "compat",
        "resume",
        "prove-at-rest",
        "failover-proof",
        "cost-report",
    ]
    for cmd in dispatch_only:
        if cmd not in registered:
            try:
                subs.add_parser(cmd)
                registered.add(cmd)
            except Exception:
                pass

    return sorted(registered)


def generate() -> str:
    """Generate the parity matrix markdown."""
    from verdict.actions.registry import GAP, LAUNCH, MACHINE_ONLY, list_actions

    actions = {spec.name: spec for spec in list_actions()}
    action_by_command: dict[str, str] = {}
    for spec in actions.values():
        parts = spec.name.split(".")
        if len(parts) == 2:
            action_by_command.setdefault(parts[0], spec.name)
        else:
            action_by_command[spec.name] = spec.name

    commands = _walk_parsers()

    lines = [
        "# CLI / TUI Parity Matrix",
        "",
        "<!-- GENERATED by scripts/gen_parity_matrix.py — do not edit by hand -->",
        "",
        "| Command | Bucket | Action or Entry | TUI Section | Justification |",
        "|---------|--------|-----------------|-------------|----------------|",
    ]

    action_count = 0
    launch_count = 0
    machine_count = 0
    gap_count = 0

    for cmd in commands:
        if cmd in action_by_command:
            aname = action_by_command[cmd]
            spec = actions[aname]
            lines.append(
                f"| `{cmd}` | action | `{spec.name}` | {spec.tui_section} | {spec.summary} |"
            )
            action_count += 1
        elif cmd in LAUNCH:
            lines.append(f"| `{cmd}` | launch | — | — | {LAUNCH[cmd]} |")
            launch_count += 1
        elif cmd in MACHINE_ONLY:
            lines.append(f"| `{cmd}` | machine-only | — | — | {MACHINE_ONLY[cmd]} |")
            machine_count += 1
        elif cmd in GAP:
            lines.append(f"| `{cmd}` | gap | — | — | {GAP[cmd]} |")
            gap_count += 1
        else:
            lines.append(f"| `{cmd}` | gap | — | — | not yet classified |")
            gap_count += 1

    lines.extend(
        [
            "",
            f"**Summary:** {action_count} actions, {launch_count} launch,"
            f" {machine_count} machine-only, {gap_count} gaps",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    content = generate()
    out = Path("docs/cli/PARITY_MATRIX.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content + "\n")
    print(f"wrote {out} ({content.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
