#!/usr/bin/env python3
"""Generate docs/cli/CLI_REFERENCE.md from the real argparse tree + action registry.

Run: python scripts/gen_cli_reference.py
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any


def _walk_parser_tree(parser: argparse.ArgumentParser, prefix: str = "") -> list[dict[str, Any]]:
    """Recursively walk argparse tree and extract command/subcommand metadata."""
    entries: list[dict[str, Any]] = []

    # Find subparsers in this parser
    for action_group in parser._action_groups:
        for action in action_group._group_actions:
            if isinstance(action, argparse._SubParsersAction):
                # This parser has subcommands
                for cmd_name, subparser in sorted(action.choices.items()):
                    cmd_path = f"{prefix} {cmd_name}".strip()
                    help_text = action.choices[cmd_name].description or ""

                    # Extract arguments for this command
                    args = []
                    for arg_group in subparser._action_groups:
                        for arg_action in arg_group._group_actions:
                            if arg_action.dest not in ("help", "command"):
                                args.append(
                                    {
                                        "name": arg_action.dest,
                                        "flags": arg_action.option_strings or [arg_action.dest],
                                        "help": arg_action.help or "",
                                        "required": arg_action.required
                                        if hasattr(arg_action, "required")
                                        else False,
                                    }
                                )

                    entries.append({"command": cmd_path, "help": help_text, "arguments": args})

                    # Recursively walk subcommands
                    entries.extend(_walk_parser_tree(subparser, cmd_path))

    return entries


def _build_parser() -> argparse.ArgumentParser:
    """Build the real argparse tree from verdict.cli.main() without executing."""
    from verdict.commands import (
        parsers_autodev,
        parsers_credentials,
        parsers_harness,
        parsers_models,
        parsers_openspec,
        parsers_routing,
        parsers_runtime,
        parsers_setup,
    )

    parser = argparse.ArgumentParser(description="Verdict: policy-gated LLM Router")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    for registrar in (
        parsers_setup,
        parsers_credentials,
        parsers_routing,
        parsers_autodev,
        parsers_harness,
        parsers_runtime,
        parsers_models,
        parsers_openspec,
    ):
        registrar.register(subparsers)

    return parser


def generate() -> str:
    """Generate the CLI reference markdown."""
    from verdict.actions.registry import GAP, LAUNCH, MACHINE_ONLY, list_actions

    parser = _build_parser()

    # Get action metadata
    actions = {spec.name: spec for spec in list_actions()}
    action_by_command: dict[str, str] = {}
    for spec in actions.values():
        parts = spec.name.split(".")
        if len(parts) == 2:
            action_by_command.setdefault(parts[0], spec.name)
        else:
            action_by_command[spec.name] = spec.name

    # Get top-level commands
    top_level_commands: set[str] = set()
    for action in parser._subparsers._group_actions:
        if isinstance(action, argparse._SubParsersAction):
            top_level_commands.update(action.choices.keys())



    lines = [
        "# CLI Reference",
        "",
        "<!-- GENERATED by scripts/gen_cli_reference.py — do not edit by hand -->",
        "",
        "Complete reference of Verdict CLI commands, organized by action and bucket.",
        "",
    ]

    # Group commands by bucket
    buckets = {
        "action": {"commands": [], "label": "Interactive Actions"},
        "launch": {"commands": [], "label": "Long-Running Processes"},
        "machine_only": {"commands": [], "label": "Machine-Only (Dev/Batch)"},
        "gap": {"commands": [], "label": "Gaps (Not Yet Implemented)"},
    }

    # Classify all top-level commands
    all_commands = sorted(top_level_commands)

    for cmd in all_commands:
        if cmd in action_by_command:
            aname = action_by_command[cmd]
            spec = actions[aname]
            buckets["action"]["commands"].append((cmd, spec))
        elif cmd in LAUNCH:
            buckets["launch"]["commands"].append((cmd, LAUNCH[cmd]))
        elif cmd in MACHINE_ONLY:
            buckets["machine_only"]["commands"].append((cmd, MACHINE_ONLY[cmd]))
        elif cmd in GAP:
            buckets["gap"]["commands"].append((cmd, GAP[cmd]))
        else:
            # Likely in dispatch_only but not yet classified
            buckets["gap"]["commands"].append((cmd, "Not yet classified"))

    # Generate markdown for each bucket
    for bucket_key in ["action", "launch", "machine_only", "gap"]:
        bucket = buckets[bucket_key]
        if not bucket["commands"]:
            continue

        lines.append(f"## {bucket['label']}")
        lines.append("")

        for cmd, metadata in bucket["commands"]:
            if isinstance(metadata, str):
                # String justification (LAUNCH, MACHINE_ONLY, GAP)
                lines.append(f"### `{cmd}`")
                lines.append("")
                lines.append(f"**Bucket:** {bucket_key}")
                lines.append("")
                lines.append(f"**Status:** {metadata}")
                lines.append("")
            else:
                # ActionSpec
                lines.append(f"### `{cmd}`")
                lines.append("")
                lines.append(f"**Action:** `{metadata.name}`")
                lines.append("")
                lines.append("**Bucket:** action")
                lines.append("")
                lines.append(f"**TUI Section:** {metadata.tui_section}")
                lines.append("")
                lines.append(f"**Kind:** {metadata.kind}")
                lines.append("")
                lines.append(f"{metadata.summary}")
                lines.append("")

    return "\n".join(lines)


def main() -> None:
    content = generate()
    out = Path("docs/cli/CLI_REFERENCE.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content + "\n")
    print(f"wrote {out} ({content.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
